name: Nightly build

# Once a day
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours" ${{ github.sha }}) && echo "name=should_run::false" >> $GITHUB_STATE
        
  build:
    runs-on: ubuntu-latest
    name: Build Docker image
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ktakashi/sagittarius
          tags: |
            type=edge
          flavor: latest=false
          labels: |
            org.opencontainers.image.authors=Takashi Kato
            org.opencontainers.image.title=Sagittarius Scheme
            org.opencontainers.image.description=Sagittarius Scheme nightly build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: .ci/Dockerfile.nightly
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le,linux/riscv64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT=${{ github.sha }}
  artifact:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: ./.github/workflows/artifact.yml
    with:
      release: false
      suffix: ${{ github.run_id }}

  installer:
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    needs: [artifact]
    uses: ./.github/workflows/windows-installer.yml
    with:
      artifact-id: ${{ needs.artifact.outputs.artifact-id }}
      tar-file: ${{ needs.artifact.outputs.tar-file }}
      suffix: ${{ github.run_id }}


