name: Sagittarius PR build
on:
  pull_requests:
    branches: [ master ]

jobs:
  POSIX-Build:
    uses: ./.github/workflows/posix-build.yml
  Windows-Build:
    uses: ./.github/workflows/windows-build.yml
