name: Windows Build
on: workflow_call

jobs:
  Windows-Build:
    runs-on: ${{ matrix.images }}
    name: ${{ matrix.images }} - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]
        images: [windows-2022, windows-2025]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: target
      - name: Install current sagittarius
        working-directory: target
        run: |
          .\.ci\install-current.ps1
        shell: powershell
      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ matrix.arch }}
      - name: Pre build
        working-directory: target
        run: dist.bat gen
        shell: cmd
      - name: CMake
        working-directory: target
        run: cmake . -G "Ninja" -DSKIP_TEST_VECTOR=ON -DBUILD_TYPE=Debug
        shell: cmd
      - name: Build
        working-directory: target
        run: ninja -j8
        shell: cmd
      - name: Test
        working-directory: target
        run: ctest --output-on-failure -LE json -j8
        shell: cmd
